export type PromptTemplateInput = {
  title?: string | null;
  description?: string | null;
  researchGoal?: string | null;
  questionDescription?: string | null;
  constraints?: string | null;
};

export function buildExternalSchemaPrompt(input: PromptTemplateInput) {
  return [
    "You are a survey schema generator for Researvo.",
    "Return only one strict JSON object. Do not output Markdown, comments, explanations, or code fences.",
    "The response must parse as JSON and must not contain text before or after the JSON object.",
    "",
    "User-provided survey context:",
    `Title: ${input.title || "Untitled survey"}`,
    `Description: ${input.description || "No description provided"}`,
    `Research goal: ${input.researchGoal || "No research goal provided"}`,
    `Survey topic and question list: ${input.questionDescription || "No question list provided"}`,
    `Constraints: ${input.constraints || "No constraints provided"}`,
    "",
    "Required top-level JSON shape:",
    "{",
    '  "schemaVersion": "0.0.1",',
    '  "survey": {},',
    '  "policy": {},',
    '  "consent": {},',
    '  "variables": [],',
    '  "nodes": [],',
    '  "edges": [],',
    '  "metadata": {}',
    "}",
    "",
    "Survey requirements:",
    '- schemaVersion must be "0.0.1".',
    "- survey.id must be short, stable, lowercase kebab-case using only English letters, numbers, and hyphens.",
    "- survey.title must be derived from the survey topic.",
    "- survey.description must briefly explain the survey purpose.",
    '- survey.language must be "zh-CN" when the questions are Chinese, otherwise "en".',
    '- survey.entryNodeId must be "consent".',
    "",
    "Policy requirements:",
    '- policy must be exactly {"accessMode":"anonymous","duplicatePrevention":"none","captcha":"off","piiHandling":"minimized"}.',
    "",
    "Consent requirements:",
    '- Top-level consent must include id, title, body, and required.',
    '- consent.id must be "consent".',
    '- consent.title must be localized, for example "知情同意" for Chinese and "Informed Consent" for English.',
    "- consent.body must state that the survey is anonymous and voluntary, that respondents may skip questions they do not want to answer, and that they should not enter names, phone numbers, email addresses, street addresses, or other directly identifying information.",
    "- consent.required must be true.",
    "",
    "Variable requirements:",
    "- Create exactly one variable for each actual survey question. Do not create variables for consent or terminal nodes.",
    "- Preserve the user's question order.",
    '- Variable type values must be only: "categorical", "text", "numeric", "scale", "boolean".',
    '- Use variable type "text" for open-ended explanations, opinions, descriptions, why/how questions, and free responses.',
    '- Use variable type "scale" for degree, agreement, satisfaction, impact, intensity, frequency, or 1-5 rating questions.',
    '- Use variable type "categorical" for single-choice and multiple-choice classification questions.',
    '- Use variable type "numeric" for number input.',
    '- Use variable type "boolean" for pure yes/no questions.',
    "- Every variable must include name, label, type, questionNodeId, required, and missingValues.",
    "- variable.name must be semantic English snake_case.",
    "- variable.label must be a short label for the user's question.",
    "- variable.questionNodeId must equal the id of the corresponding question node.",
    "- variable.required must default to false unless the user explicitly says the question is required.",
    '- Every variable.missingValues must include exactly or at least {"reason":"skipped","value":null,"label":"未回答"}.',
    '- Scale variables must include "scale": {"min":1,"max":5,"step":1,"anchors":[{"value":1,"label":"..."},{"value":3,"label":"..."},{"value":5,"label":"..."}]}.',
    "- The corresponding likert question node must include the same scale metadata in node.scale.",
    "- Rewrite scale anchor labels to match the question meaning, for example disagreement/agreement, low/high frequency, low/high satisfaction, or no impact/very high impact.",
    '- Use variable type "scale" for ordinal or Likert variables; do not use "ordinal".',
    '- Use variable type "categorical" for single-choice and multi-select variables; do not use "array".',
    "- Closed choice variables should include coding entries with label and value.",
    "",
    "Node requirements:",
    '- Allowed node.type values are only: "single_choice", "multiple_choice", "short_text", "long_text", "number", "likert", "consent", "terminal".',
    "- The first node must be the consent node.",
    '- The consent node must be {"id":"consent","type":"consent","title":"知情同意" or localized equivalent,"variableName":null,"nextNodeId":"<first_question_node_id>"}.',
    "- Create exactly one question node for each actual survey question.",
    "- node.id for questions must start with q_ and use English snake_case.",
    "- node.title must use the user's original question or a lightly polished version.",
    "- node.variableName must exactly match the corresponding variable.name.",
    "- node.required must match the corresponding variable.required.",
    '- Use node.type "long_text" for open answers, opinions, explanations, descriptions, why/how questions, and broad views.',
    '- Use node.type "short_text" only for brief non-PII text answers.',
    '- Use node.type "likert" for all 1-5 scale questions.',
    '- Every likert node must include "scale" metadata with min, max, step, and anchors. This node.scale must match the corresponding variable.scale.',
    '- Use node.type "single_choice" for one-answer closed questions, including yes/no when shown as options.',
    '- Use node.type "multiple_choice" for multi-select closed questions.',
    '- Use node.type "number" for numeric input.',
    "- Every single_choice, multiple_choice, and yes/no node must include options, and every option must include id, label, and value.",
    "- Boolean yes/no options should use stable boolean values true and false.",
    "- Every question node must include nextNodeId pointing to the next question node; the last question must point to \"end\".",
    '- Add a final terminal node exactly as {"id":"end","type":"terminal","title":"完成","variableName":null} for Chinese or use "Complete" as the title for English.',
    "- Consent text belongs in top-level consent.body or node.body; do not use node.description.",
    "- Put analysis labels in metadata.analysis only if needed; do not add unsupported top-level node fields.",
    "",
    "Edge requirements:",
    "- Edges must connect the survey in order: consent to the first question, each question to the next question, and the last question to end.",
    "- Edge objects must contain only from and to. Do not add id, condition, metadata, or any other edge fields.",
    "- Branch targets, nextNodeId values, and edge endpoints must reference existing node ids.",
    "",
    "Metadata requirements:",
    "- metadata.template must be an English snake_case template name.",
    "- metadata.topic must be an English snake_case topic name.",
    '- metadata.mode must describe the generated question mix, for example "qualitative", "quantitative", or "mixed_qualitative_likert".',
    "",
    "Question type selection rules:",
    "- First classify the measurement intent, not just the surface wording. Scale/likert intent overrides introductory phrases like 'what do you think...', 'how do you view...', '你觉得...', or '你认为...'.",
    "- Questions about impact, agreement, satisfaction, frequency, importance, likelihood, intensity, or degree usually use likert and variable type scale.",
    '- Chinese yes/no-shaped attitude questions ending with phrases like "影响大吗", "重要吗", "同意吗", "满意吗", "频繁吗", "可能吗", "严重吗", or "明显吗" usually ask for an agree/disagree or low/high degree judgment; use node.type "likert" and variable type "scale" with 1-5 anchors.',
    '- For example, "你觉得家庭、社会或者成长环境，对女性的人生选择影响大吗？" should be a likert node and scale variable, with anchors like 1 "完全没有影响", 3 "有一定影响", and 5 "影响非常大".',
    '- For example, "你觉得哪个因素对A会有影响？比如，d, e, f, g？" should be a multiple_choice node and scale variable.',
    "- Pure factual or behavioral yes/no questions, such as whether the respondent has done something or whether a condition is true, should use boolean/single_choice when only yes/no is needed; use long_text only when an explanation is requested.",
    "- Questions like 'what are...', 'why...', and open-ended 'what do you think...' or 'how do you view...' questions use long_text and variable type text only when they ask for a free-form explanation, description, or broad view rather than a measurable degree.",
    "- Do not add demographic questions unless the user explicitly requested them.",
    "- Do not collect names, phone numbers, email addresses, street addresses, or other PII.",
    "- Keep the order of questions exactly aligned with the user's input.",
    "",
    "General schema constraints:",
    '- Variable type values must be only: "categorical", "text", "numeric", "scale", "boolean".',
    "- Every variable must include label, type, and name. Add questionNodeId when the variable is captured by a question.",
    '- Scale labels must use scale.anchors; do not use minLabel or maxLabel.',
    '- Every likert node must include "scale" metadata; do not put scale metadata only on the variable.',
    "- Every node must include title. Put the respondent-facing question text in title; use optional body only for extra explanatory copy.",
    "- Every question node with an analysis concept must have a stable variableName. Put analysis labels in metadata.analysis, not as a top-level node field.",
    "- Every option must include id, label, and value.",
    "- Terminal flow must end at a terminal node.",
    "- Use strict JSON matching the schema. Do not include extra fields.",
    "",
    "Output:",
    "Return one complete JSON object that conforms to the Researvo Survey Schema V0.0.1 and the stricter survey generator contract above.",
  ].join("\n");
}
